#!/usr/bin/env python3
"""Generate the v2 reference guide from framework.v2.json.

Writes reference/framework-v2.md (EN), reference/framework-v2.pt-br.md
and reference/framework-v2.es.md: scoring method, a worked example
computed by scripts/engine_v2.py on the illustrative mock, and the full
catalogue of dimensions and questions with anchors, evidence examples,
references and v1 lineage. Also writes one page per dimension in
reference/dimensions/ (D1.md ... D9.md with .pt-br.md and .es.md copies,
plus an index) for workshops and owners. Do not edit the output by hand.

Usage:
    python3 scripts/generate_v2_reference.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import engine_v2 as v2  # noqa: E402

OUT = {"en": "reference/framework-v2.md",
       "pt-br": "reference/framework-v2.pt-br.md",
       "es": "reference/framework-v2.es.md"}

T = {
    "en": {
        "switch": "🌐 English · [Português (Brasil)](framework-v2.pt-br.md)"
                  " · [Español](framework-v2.es.md)",
        "title": "AI Maturity framework v2: reference guide",
        "intro": "Generated from `framework.v2.json` (framework {v}) by "
                 "`scripts/generate_v2_reference.py`. The source of truth "
                 "is [the v2 spec](../collection/AI-Maturity-Form-Questions_"
                 "v2.md). Do not edit this file by hand.",
        "method": "Scoring method",
        "rules": [
            "Answer value: L0 to L4 = 0 to 4. NA and blank answers are "
            "excluded.",
            "Question score: mean of the respondent values.",
            "Dimension score: mean of its question scores. A dimension "
            "with no answered question has no score.",
            "Overall: weighted mean of the dimensions with a score "
            "(weights 1.0 by default, allowed {w0} to {w1}).",
            "Coverage: OK from {ok} questions with a score, WARNING from "
            "{warn}, BLOCKED below.",
            "Gap = target (default {target}) minus score. Priority score "
            "= weight × gap: P0 from {p0}, P1 from {p1}, P2 from {p2}, "
            "else P3.",
            "Flags: low confidence (more than {na}% NA), amplification "
            "risk (D5, D6 or D8 one band below overall), perception gap "
            "(executives vs hands-on, at least {n} each), scope caveat, "
            "unverified L3/L4 (less than {ev}% of answers with evidence), "
            "respondent divergence (standard deviation of respondent "
            "dimension scores of {sd} or more, at least {n} respondents).",
            "Evidence cross-checks, when the files exist: the repository "
            "scan (RAMP levels [47]) caps D4-Q4 by the share of "
            "repositories with committed AI configuration, and Copilot "
            "usage metrics [6] cap D4-Q1 by the adoption phases. The "
            "report flags answers above what the evidence supports.",
        ],
        "bands": "Level bands",
        "example": "Worked example: {d} on the illustrative mock",
        "example_intro": "The mock (`responses.v2.json.example`, {n} "
                         "illustrative respondents) gives these values. "
                         "They come from `scripts/engine_v2.py`.",
        "q": "Question", "score": "Score", "n": "Answers", "na": "NA",
        "dim_line": "{d} score = mean of the {k} question scores = "
                    "**{s}** ({label}). Gap to {t} = {g}; priority score "
                    "= {w} × {g} = {p} → **{prio}**.",
        "overall_line": "Overall = mean of the 9 dimension scores = "
                        "**{s}** ({label}).",
        "catalogue": "Dimensions and questions",
        "why": "Why it matters", "strategies": "Strategies",
        "group": "Report group",
        "evidence": "Evidence examples", "basis": "Basis",
        "lineage": "v1 lineage", "none": "None (new in v2)",
        "partial": "partial", "unit": "Unit", "audience": "Audience",
        "pe": "Platform engineering readiness", "yes": "yes",
        "refs": "References", "level": "Level",
        "scope": "Scope note", "page": "Dimension page",
        "d_title": "{d}: {name}", "d_index": "Dimension pages",
        "d_index_intro": "One page per dimension, generated from "
                         "`framework.v2.json` for workshops and dimension "
                         "owners. Scores and priorities come from the "
                         "client's own reports.",
        "d_nav": "[All dimensions](README.md) · [Reference guide]"
                 "(../framework-v2.md)",
        "d_how": "How to use this page: agree the current level of each "
                 "question with its evidence, then plan the next step "
                 "from the L3 anchor (or the L4 anchor when L3 already "
                 "holds).",
        "d_survey": "Developer Survey context",
        "d_survey_line": "{ds} informs {qs}.",
        "d_questions": "Questions", "d_refs": "References cited here",
    },
    "pt-br": {
        "switch": "🌐 [English](framework-v2.md) · Português (Brasil)"
                  " · [Español](framework-v2.es.md)",
        "title": "Framework AI Maturity v2: guia de referência",
        "intro": "Gerado a partir de `framework.v2.json` (framework {v}) "
                 "por `scripts/generate_v2_reference.py`. A fonte da "
                 "verdade é [a especificação v2](../collection/AI-Maturity-"
                 "Form-Questions_v2.md), em inglês, com tradução em "
                 "[AI-Maturity-Form-Questions_v2.pt-br.md](../collection/"
                 "AI-Maturity-Form-Questions_v2.pt-br.md). Não edite este "
                 "arquivo à mão.",
        "method": "Método de pontuação",
        "rules": [
            "Valor da resposta: L0 a L4 = 0 a 4. Respostas NA e em "
            "branco são excluídas.",
            "Score da pergunta: média dos valores dos respondentes.",
            "Score da dimensão: média dos scores das perguntas. Uma "
            "dimensão sem nenhuma pergunta respondida fica sem score.",
            "Geral: média ponderada das dimensões com score (pesos 1,0 "
            "por padrão, permitido de {w0} a {w1}).",
            "Cobertura: OK a partir de {ok} perguntas com score, WARNING "
            "a partir de {warn}, BLOCKED abaixo disso.",
            "Gap = alvo (padrão {target}) menos score. Prioridade = peso "
            "× gap: P0 a partir de {p0}, P1 a partir de {p1}, P2 a partir "
            "de {p2}, senão P3.",
            "Alertas: baixa confiança (mais de {na}% NA), risco de "
            "amplificação (D5, D6 ou D8 uma faixa abaixo do geral), "
            "diferença de percepção (executivos vs hands-on, ao menos {n} "
            "de cada), ressalva de escopo, L3/L4 não verificado (menos de "
            "{ev}% das respostas com evidência), divergência entre "
            "respondentes (desvio padrão das notas de dimensão por "
            "respondente de {sd} ou mais, com ao menos {n} respondentes).",
            "Checagens cruzadas, quando os arquivos existem: o scan de "
            "repositórios (níveis RAMP [47]) limita D4-Q4 pela fração de "
            "repositórios com configuração de IA versionada, e as métricas "
            "de uso do Copilot [6] limitam D4-Q1 pelas fases de adoção. O "
            "relatório sinaliza respostas acima do que a evidência "
            "sustenta.",
        ],
        "bands": "Faixas de nível",
        "example": "Exemplo resolvido: {d} no mock ilustrativo",
        "example_intro": "O mock (`responses.v2.json.example`, {n} "
                         "respondentes ilustrativos) gera estes valores, "
                         "calculados por `scripts/engine_v2.py`.",
        "q": "Pergunta", "score": "Score", "n": "Respostas", "na": "NA",
        "dim_line": "Score de {d} = média dos {k} scores das perguntas = "
                    "**{s}** ({label}). Gap até {t} = {g}; prioridade = "
                    "{w} × {g} = {p} → **{prio}**.",
        "overall_line": "Geral = média dos 9 scores de dimensão = "
                        "**{s}** ({label}).",
        "catalogue": "Dimensões e perguntas",
        "why": "Por que importa", "strategies": "Estratégias",
        "group": "Grupo do relatório",
        "evidence": "Exemplos de evidência", "basis": "Base",
        "lineage": "Origem na v1", "none": "Nenhuma (nova na v2)",
        "partial": "parcial", "unit": "Unidade", "audience": "Público",
        "pe": "Prontidão de platform engineering", "yes": "sim",
        "refs": "Referências", "level": "Nível",
        "scope": "Nota de escopo", "page": "Página da dimensão",
        "d_title": "{d}: {name}", "d_index": "Páginas por dimensão",
        "d_index_intro": "Uma página por dimensão, gerada a partir de "
                         "`framework.v2.json` para workshops e "
                         "responsáveis por dimensão. Notas e prioridades "
                         "vêm dos relatórios do próprio cliente.",
        "d_nav": "[Todas as dimensões](README.pt-br.md) · [Guia de "
                 "referência](../framework-v2.pt-br.md)",
        "d_how": "Como usar esta página: acorde o nível atual de cada "
                 "pergunta com as evidências e planeje o próximo passo a "
                 "partir da âncora L3 (ou da âncora L4, quando a L3 já é "
                 "atendida).",
        "d_survey": "Contexto do Developer Survey",
        "d_survey_line": "{ds} informa {qs}.",
        "d_questions": "Perguntas", "d_refs": "Referências citadas aqui",
    },
    "es": {
        "switch": "🌐 [English](framework-v2.md) · [Português (Brasil)]"
                  "(framework-v2.pt-br.md) · Español",
        "title": "Framework AI Maturity v2: guía de referencia",
        "intro": "Generado desde `framework.v2.json` (framework {v}) por "
                 "`scripts/generate_v2_reference.py`. La fuente de verdad "
                 "es [la especificación v2](../collection/AI-Maturity-Form-"
                 "Questions_v2.md), en inglés, con traducción en "
                 "[AI-Maturity-Form-Questions_v2.es.md](../collection/"
                 "AI-Maturity-Form-Questions_v2.es.md). No edites este "
                 "archivo a mano.",
        "method": "Método de puntuación",
        "rules": [
            "Valor de la respuesta: L0 a L4 = 0 a 4. Las respuestas NA y "
            "en blanco se excluyen.",
            "Puntaje de la pregunta: media de los valores de las "
            "personas.",
            "Puntaje de la dimensión: media de los puntajes de sus "
            "preguntas. Una dimensión sin preguntas respondidas no tiene "
            "puntaje.",
            "General: media ponderada de las dimensiones con puntaje "
            "(pesos 1,0 por defecto, permitido de {w0} a {w1}).",
            "Cobertura: OK desde {ok} preguntas con puntaje, WARNING desde "
            "{warn}, BLOCKED por debajo.",
            "Brecha = objetivo (por defecto {target}) menos puntaje. "
            "Prioridad = peso × brecha: P0 desde {p0}, P1 desde {p1}, P2 "
            "desde {p2}, si no P3.",
            "Alertas: baja confianza (más del {na}% NA), riesgo de "
            "amplificación (D5, D6 o D8 un rango por debajo del general), "
            "brecha de percepción (ejecutivos vs hands-on, al menos {n} "
            "de cada uno), salvedad de alcance, L3/L4 no verificado "
            "(menos del {ev}% de respuestas con evidencia), divergencia "
            "entre personas encuestadas (desviación estándar de los "
            "puntajes de dimensión por persona de {sd} o más, con al menos "
            "{n} personas).",
            "Verificaciones cruzadas, cuando existen los archivos: el "
            "escaneo de repositorios (niveles RAMP [47]) limita D4-Q4 por "
            "la fracción de repositorios con configuración de IA "
            "versionada, y las métricas de uso de Copilot [6] limitan "
            "D4-Q1 por las fases de adopción. El informe señala respuestas "
            "por encima de lo que sostiene la evidencia.",
        ],
        "bands": "Rangos de nivel",
        "example": "Ejemplo resuelto: {d} en el mock ilustrativo",
        "example_intro": "El mock (`responses.v2.json.example`, {n} "
                         "personas ilustrativas) da estos valores, "
                         "calculados por `scripts/engine_v2.py`.",
        "q": "Pregunta", "score": "Puntaje", "n": "Respuestas",
        "na": "NA",
        "dim_line": "Puntaje de {d} = media de los {k} puntajes de las "
                    "preguntas = **{s}** ({label}). Brecha hasta {t} = "
                    "{g}; prioridad = {w} × {g} = {p} → **{prio}**.",
        "overall_line": "General = media de los 9 puntajes de dimensión = "
                        "**{s}** ({label}).",
        "catalogue": "Dimensiones y preguntas",
        "why": "Por qué importa", "strategies": "Estrategias",
        "group": "Grupo del informe",
        "evidence": "Ejemplos de evidencia", "basis": "Base",
        "lineage": "Origen en v1", "none": "Ninguno (nueva en v2)",
        "partial": "parcial", "unit": "Unidad", "audience": "Audiencia",
        "pe": "Preparación de platform engineering", "yes": "sí",
        "refs": "Referencias", "level": "Nivel",
        "scope": "Nota de alcance", "page": "Página de la dimensión",
        "d_title": "{d}: {name}", "d_index": "Páginas por dimensión",
        "d_index_intro": "Una página por dimensión, generada desde "
                         "`framework.v2.json` para talleres y responsables "
                         "de dimensión. Los puntajes y prioridades vienen "
                         "de los informes del propio cliente.",
        "d_nav": "[Todas las dimensiones](README.es.md) · [Guía de "
                 "referencia](../framework-v2.es.md)",
        "d_how": "Cómo usar esta página: acuerden el nivel actual de cada "
                 "pregunta con sus evidencias y planifiquen el siguiente "
                 "paso desde el ancla L3 (o el ancla L4 cuando la L3 ya "
                 "se cumple).",
        "d_survey": "Contexto del Developer Survey",
        "d_survey_line": "{ds} informa {qs}.",
        "d_questions": "Preguntas", "d_refs": "Referencias citadas aquí",
    },
}

EXAMPLE_DIMENSION = "D8"
SUFFIX = {"en": ".md", "pt-br": ".pt-br.md", "es": ".es.md"}
SWITCH = {"en": "🌐 English · [Português (Brasil)]({b}.pt-br.md) · "
                "[Español]({b}.es.md)",
          "pt-br": "🌐 [English]({b}.md) · Português (Brasil) · "
                   "[Español]({b}.es.md)",
          "es": "🌐 [English]({b}.md) · [Português (Brasil)]"
                "({b}.pt-br.md) · Español"}


def question_block(fw: dict, q: dict, lang: str) -> list[str]:
    t = T[lang]
    out = [f"### {q['id']}: {v2.tr(q['title'], lang)}", "",
           f"> {v2.tr(q['text'], lang)}", ""]
    if q.get("scope_note"):
        out += [f"_{t['scope']}: {v2.tr(q['scope_note'], lang)}_", ""]
    anchors = q["anchors"]
    if anchors.get("l1_l2"):
        out.append(f"- **L1-L2:** {v2.tr(anchors['l1_l2'], lang)}")
    out += [f"- **L3:** {v2.tr(anchors['l3'], lang)}",
            f"- **L4:** {v2.tr(anchors['l4'], lang)}",
            f"- **{t['evidence']}:** {v2.tr(q['evidence_examples'], lang)}",
            f"- **{t['basis']}:** " + " ".join(f"[{n}]" for n in q["basis"]),
            ""]
    return out


def dimension_page(fw: dict, d: dict, lang: str) -> str:
    t = T[lang]
    groups = {g["id"]: g["name"][lang] for g in fw["report_groups"]}
    names = {s["id"]: s["name"] for s in fw["strategies"]}
    qids = {q["id"] for q in d["questions"]}
    out = [SWITCH[lang].format(b=d["id"]), "",
           f"# {t['d_title'].format(d=d['id'], name=v2.tr(d['name'], lang))}",
           "", t["d_nav"], "",
           f"**{t['why']}:** {v2.tr(d['why_it_matters'], lang)}", "",
           f"**{t['strategies']}:** "
           + ", ".join(f"{s} {names[s]}" for s in d["strategies"])
           + f" · **{t['group']}:** {d['group']} ({groups[d['group']]})",
           "", t["d_how"], "", f"## {t['d_questions']}", ""]
    cited: set[int] = set()
    for q in d["questions"]:
        out += question_block(fw, q, lang)
        cited.update(q["basis"])
    survey = [(ds, [q for q in qs if q in qids])
              for ds, qs in (fw.get("survey_crosswalk") or {}).items()]
    survey = [(ds, qs) for ds, qs in survey if qs]
    if survey:
        out += [f"## {t['d_survey']}", ""]
        out += [f"- {t['d_survey_line'].format(ds=ds, qs=', '.join(qs))}"
                for ds, qs in survey]
        out.append("")
    out += [f"## {t['d_refs']}", ""]
    for r in fw["references"]:
        if r["n"] in cited:
            out.append(f"- [{r['n']}] {r['text']}")
    return "\n".join(out).rstrip() + "\n"


def dimension_index(fw: dict, lang: str) -> str:
    t = T[lang]
    base = {"en": "framework-v2.md", "pt-br": "framework-v2.pt-br.md",
            "es": "framework-v2.es.md"}[lang]
    out = [SWITCH[lang].format(b="README"), "", f"# {t['d_index']}", "",
           t["d_index_intro"], "", f"[{t['title']}](../{base})", "",
           f"| ID | {t['catalogue']} | {t['group']} | {t['d_questions']} |",
           "| --- | --- | --- | ---: |"]
    for d in fw["dimensions"]:
        page = f"{d['id']}{SUFFIX[lang]}"
        out.append(f"| [{d['id']}]({page}) | {v2.tr(d['name'], lang)} | "
                   f"{d['group']} | {len(d['questions'])} |")
    return "\n".join(out) + "\n"


def outputs(fw: dict) -> dict[str, str]:
    files = {rel: render(fw, lang) for lang, rel in OUT.items()}
    for lang, suffix in SUFFIX.items():
        index = "README" + suffix
        files[f"reference/dimensions/{index}"] = dimension_index(fw, lang)
        for d in fw["dimensions"]:
            files[f"reference/dimensions/{d['id']}{suffix}"] = \
                dimension_page(fw, d, lang)
    return files


def num(v: float | None, lang: str) -> str:
    if v is None:
        return "-"
    s = f"{v:.2f}"
    return s.replace(".", ",") if lang != "en" else s


def render(fw: dict, lang: str) -> str:
    t = T[lang]
    sc = fw["scoring"]
    mock = json.loads((ROOT / "responses.v2.json.example").read_text(
        encoding="utf-8"))
    scores = v2.compute_scores(fw, mock, lang)
    gaps = {g["dimension_id"]: g for g in
            v2.compute_gaps(fw, mock, lang)["gaps"]}
    out = [t["switch"], "", f"# {t['title']}", "",
           t["intro"].format(v=fw["version"]), "",
           f"## {t['method']}", ""]
    cuts = sc["priority_cuts"]
    w0, w1 = sc["dimension_weight_range"]
    for rule in t["rules"]:
        out.append("- " + rule.format(
            w0=num(w0, lang), w1=num(w1, lang), ok=sc["coverage_ok_min"],
            warn=sc["coverage_warning_min"],
            target=num(sc["default_target"], lang),
            p0=num(cuts["P0"], lang), p1=num(cuts["P1"], lang),
            p2=num(cuts["P2"], lang),
            na=round(sc["low_confidence_na_share"] * 100),
            n=sc["persona_min_n"],
            ev=round(sc["unverified_evidence_share"] * 100),
            sd=num(sc["divergence_sd_min"], lang)))
    out += ["", f"### {t['bands']}", "",
            f"| {t['level']} | {t['score']} |", "| --- | --- |"]
    for i, b in enumerate(fw["level_bands"]):
        close = "]" if i == len(fw["level_bands"]) - 1 else ")"
        out.append(f"| {b['level']} {fw['level_names'][lang][b['level']]}"
                   f" | [{num(b['min'], lang)}; {num(b['max'], lang)}"
                   f"{close} |")

    did = EXAMPLE_DIMENSION
    dim = next(d for d in fw["dimensions"] if d["id"] == did)
    sdim = next(d for d in scores["dimensions"] if d["id"] == did)
    qs = {q["id"]: q for q in scores["questions"]}
    out += ["", f"### {t['example'].format(d=did)}", "",
            t["example_intro"].format(n=scores["metadata"]["respondents"]),
            "", f"| {t['q']} | {t['score']} | {t['n']} | {t['na']} |",
            "| --- | ---: | ---: | ---: |"]
    for q in dim["questions"]:
        s = qs[q["id"]]
        out.append(f"| {q['id']} {v2.tr(q['title'], lang)} | "
                   f"{num(s['score'], lang)} | {s['n']} | {s['na']} |")
    g = gaps.get(did)
    out += ["", t["dim_line"].format(
        d=did, k=sdim["answered"], s=num(sdim["score"], lang),
        label=sdim["label"],
        t=num(g["target_level"] if g else sc["default_target"], lang),
        g=num(g["gap_size"] if g else 0.0, lang),
        w=num(sdim["weight"], lang),
        p=num(g["priority_score"] if g else 0.0, lang),
        prio=g["priority"] if g else "-"), "",
        t["overall_line"].format(s=num(scores["overall"]["score"], lang),
                                 label=scores["overall"]["label"]), ""]

    groups = {g["id"]: g["name"][lang] for g in fw["report_groups"]}
    out += [f"## {t['catalogue']}", ""]
    for d in fw["dimensions"]:
        out += [f"### {d['id']}: {v2.tr(d['name'], lang)}", "",
                f"**{t['why']}:** {v2.tr(d['why_it_matters'], lang)}", "",
                f"**{t['page']}:** [dimensions/{d['id']}{SUFFIX[lang]}]"
                f"(dimensions/{d['id']}{SUFFIX[lang]})", "",
                f"**{t['strategies']}:** {', '.join(d['strategies'])} · "
                f"**{t['group']}:** {d['group']} ({groups[d['group']]})",
                ""]
        for q in d["questions"]:
            out += [f"#### {q['id']}: {v2.tr(q['title'], lang)}", "",
                    v2.tr(q["text"], lang), ""]
            if q.get("scope_note"):
                out += [f"_{t['scope']}: {v2.tr(q['scope_note'], lang)}_",
                        ""]
            for i, opt in enumerate(fw["options"][lang][:5]):
                out.append(f"- {opt}")
            anchors = q["anchors"]
            if anchors.get("l1_l2"):
                out.append(f"- L1-L2: {v2.tr(anchors['l1_l2'], lang)}")
            out += [f"- L3: {v2.tr(anchors['l3'], lang)}",
                    f"- L4: {v2.tr(anchors['l4'], lang)}", ""]
            lineage = ", ".join(
                x["id"] + (f" ({t['partial']})" if x.get("partial")
                           else "") for x in q["v1_lineage"]) or t["none"]
            meta = [f"**{t['evidence']}:** "
                    f"{v2.tr(q['evidence_examples'], lang)}",
                    f"**{t['basis']}:** "
                    + " ".join(f"[{n}]" for n in q["basis"]),
                    f"**{t['lineage']}:** {lineage}",
                    f"**{t['unit']}:** {q['unit']} · **{t['audience']}:** "
                    + ", ".join(q["audience"])
                    + (f" · **{t['pe']}:** {t['yes']}" if q["pe"] else "")]
            out += ["  \n".join(meta), ""]
    out += [f"## {t['refs']}", ""]
    for r in fw["references"]:
        out.append(f"{r['n']}. {r['text']}")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if an output is missing or stale")
    args = ap.parse_args()
    fw = json.loads((ROOT / "framework.v2.json").read_text("utf-8"))
    stale = []
    (ROOT / "reference" / "dimensions").mkdir(exist_ok=True)
    for rel, text in outputs(fw).items():
        path = ROOT / rel
        if args.check:
            if not path.exists() or path.read_text("utf-8") != text:
                stale.append(rel)
            continue
        path.write_text(text, encoding="utf-8")
    if not args.check:
        print(f"✓ reference/framework-v2 (3 languages) and "
              f"reference/dimensions/ ({len(outputs(fw)) - 3} pages)")
    if stale:
        print("✗ Stale: " + ", ".join(stale)
              + ". Run python3 scripts/generate_v2_reference.py",
              file=sys.stderr)
        return 1
    if args.check:
        print("✓ reference guide and dimension pages up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
